export const trade = [
    {
        key: 1,
        currency1: 'USD',
        currency2: 'RMB',
        detail: 'United State dollars to Chinese Yuan',
        sell: 5.3593,
        buy: 5.5927,
    }, 
    {
        key: 2,
        currency1: 'USD',
        currency2: 'RMB',
        detail: 'United State dollars to Chinese Yuan',
        sell: 5.3593,
        buy: 5.5927,
    }, 
    {
        key: 3,
        currency1: 'USD',
        currency2: 'RMB',
        detail: 'United State dollars to Chinese Yuan',
        sell: 5.3593,
        buy: 5.5927,
    }, 
    {
        key: 4,
        currency1: 'USD',
        currency2: 'RMB',
        detail: 'United State dollars to Chinese Yuan',
        sell: 5.3593,
        buy: 5.5927,
    }, 
    {
        key: 5,
        currency1: 'USD',
        currency2: 'RMB',
        detail: 'United State dollars to Chinese Yuan',
        sell: 5.3593,
        buy: 5.5927,
    }, 
    {
        key: 6,
        currency1: 'USD',
        currency2: 'RMB',
        detail: 'United State dollars to Chinese Yuan',
        sell: 5.3593,
        buy: 5.5927,
    }, 
    {
        key: 7,
        currency1: 'USD',
        currency2: 'RMB',
        detail: 'United State dollars to Chinese Yuan',
        sell: 5.3593,
        buy: 5.5927,
    },  
    
]