export const userList = [
    {
        key: 1,
        username: 'John Smith',
        path: '/',
       status:'Initialised',
        dollar : 'USD 400',
    },
    {
        key: 2,
        username: 'John Smith',
        path: '/',
       status:'Initialised',
        dollar : 'USD 400',
    },
    {
        key: 3,
        username: 'John Smith',
        path: '/',
       status:'Initialised',
        dollar : 'USD 400',
    },
    {
        key: 4,
        username: 'John Smith',
        path: '/',
       status:'Initialised',
        dollar : 'USD 400',
    },
    {
        key: 5,
        username: 'John Smith',
        path: '/',
        status:'cleared',
        dollar : 'USD 400',
    },
    {
        key: 6,
        username: 'John Smith',
        path: '/',
        status:'cleared',
        dollar : 'USD 400',
    },
    {
        key: 7,
        username: 'John Smith',
        path: '/',
        status:'cleared',
        dollar : 'USD 400',
    },
    {
        key: 8,
        username: 'John Smith',
        path: '/',
        status:'cleared',
        dollar : 'USD 400',
    },
    {
        key: 9,
        username: 'John Smith',
        path: '/',
        status:'cleared',
        dollar : 'USD 400',
    },
    {
        key: 10,
        username: 'John Smith',
        path: '/',
        status:'Initialised',
        dollar : 'USD 400',
    },
    
]